global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "log-analyzer"
    static_configs:
      - targets: ["log-analyzer:8200"]
    metrics_path: /metrics

  - job_name: "log-ml"
    static_configs:
      - targets: ["log-ml:3050"]
    metrics_path: /metrics
